baseurl = "https://reconlearn.org/"
theme = "hugo-casper-two"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = "reconlearn"
# Enable Google Analytics by entering your tracking code
# googleAnalytics = ""
# Ignore the following extensions
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$","^README"]
paginate        = 6
uglyurls = true
preserveTaxonomyNames = true
pygmentsStyle = "monokai"
pygmentsCodeFences = true

[taxonomies]
  category = "categories"
  license = "licenses"
  author = "authors"
  topic = "topics"

[params]
  title = "RECON learn"
  # Use custom.css for your custom styling
  style = "default"
  subtitle = "Free and open training resources to respond to outbreaks, health emergencies and humanitarian crises."
  copyright = "©2018 RECON"
  description = "For more about the R Epidemics Consortium (RECON), visit our website: https://repidemicsconsortium.org"
  singleViewStyle = "casper"
  pageNotFoundTitle = "404 - Page not found"
  customCSS = ["css/custom.css"]
  
  email         = "thibautjombart@gmail.com"
  twitterName    = "teebzr"
  githubName = "reconhub/learn"
  
  logo = "img/logo/learnBlueAndWhite.png"
  orgName = "RECON"
  orgWebsite = "https://repidemicsconsortium.org"
  orgDescription = "For more about the R Epidemics Consortium (RECON), visit our website: https://repidemicsconsortium.org"
  authorAvatar = "img/user.png"

  showSupport = true


[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200
  
[[menu.main]]
  name = "Practicals"
  url = "/categories/practicals.html"
  weight = 99
  pre = "<i class='far fa-align-justify'></i>"
  
[[menu.main]]
  name = "Case Studies"
  url = "/categories/case-studies.html"
  weight = 99
  pre = "<i class='far fa-align-justify'></i>"

[[menu.main]]
  name = "Lectures"
  url = "/categories/lectures.html"
  weight = 99
  pre = "<i class='far fa-align-justify'></i>"
  
[[menu.main]]
  name = "Topics"
  url = "/topics.html"
  weight = 98
  pre = "<i class='far fa-align-justify'></i>"

[[menu.main]]
  name = "Authors"
  url = "/authors.html"
  weight = 98
  pre = "<i class='far fa-align-justify'></i>"

[[menu.main]]
  name = "Licenses"
  url = "/licenses.html"
  weight = 97
  pre = "<i class='far fa-align-justify'></i>"
  
[[menu.main]]
  name = "About"
  url = "/about.html"
  weight = 90
  
[[menu.main]]
  name = "Contact"
  url = "/contact.html"
  weight = 89

  
